### ISSUE TITLE
Plugin won't load on newer versions of HA

### ISSUE THREAD

**Issue by B1223GS87** [toscano/hass-autonomic#4]
Thank you for this great plug-in for Autonomic!

The docker that I use for Home Assistant seems to have upgraded the python version that was previously used, which caused this to stop working with the error. 
2023-06-11 18:20:46.214 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.autonomic.media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/autonomic/media_player.py", line 146, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
_AttributeError: module 'asyncio' has no attribute 'coroutine'_

**Comment by toscano** [comment]
@B1223GS87 thanks for this report. Yes. I have the same issue now that I've updated my instance of HA. I'll try to take a look tomorrow.

https://stackoverflow.com/questions/74345065/attributeerror-module-asyncio-has-no-attribute-coroutine-in-python-3-11/74345066#74345066

**Comment by toscano** [comment]
Closed by PR #5
